version: '3.8'
services:
  reservation_test:
    image: ubuntu:22.04
    command: nvidia-smi -L
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
  nvidia_runtime_test:
    image: ubuntu:22.04
    command: nvidia-smi -L
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  cdi_device:
    image: ubuntu:22.04
    command: nvidia-smi -L
    devices:
     - nvidia.com/gpu=all
  # cdi_driver_reservation_test:
  #   image: ubuntu:22.04
  #   command: nvidia-smi -L
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #          - driver: cdi
  #            device_ids:
  #               - nvidia.com/gpu=all
  #               - nvidia.com/gds=all
  #               - nvidia.com/mofed=all
